// apps/web-admin-ui/src/components/login-modal.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSetAtom } from "jotai";
import { ApiError, postJson, sanitizeErrorMessage } from "@/api";
import { authRequiredAtom, authErrorAtom, navTabAtom } from "@/stores/atoms";
import type { AdminResponse } from "@/stores/types";
import { Btn, TextInput } from "@/components/ui/controls";
import { AppDialog, AppDialogBody, AppDialogContent, AppDialogFooter, AppDialogHeader } from "@/components/ui/app-dialog";

type LoginResponse = { user: string; requires_password_change?: boolean };
const MAX_USERNAME_CHARS = 64;
const MAX_PASSWORD_CHARS = 256;

export function LoginModal({
  open,
  error: _error,
  onClearError,
}: {
  open: boolean;
  error: string | null;
  onClearError: () => void;
}) {
  const setAuthRequired = useSetAtom(authRequiredAtom);
  const setAuthError = useSetAtom(authErrorAtom);
  const setNavTab = useSetAtom(navTabAtom);
  void _error;

  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("admin");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!open) return;
    setUsername("admin");
    setPassword("admin");
  }, [open]);

  const usernameError = useMemo(() => {
    const u = username.trim();
    if (!u) return null;
    if (u.length > MAX_USERNAME_CHARS) return `Username too long [max ${MAX_USERNAME_CHARS} chars]`;
    if ([...u].some((ch) => /[\x00-\x1F\x7F]/.test(ch))) return "Username contains invalid characters";
    return null;
  }, [username]);

  const canSubmit = useMemo(() => {
    const u = username.trim();
    return u.length > 0 && u.length <= MAX_USERNAME_CHARS && password.length > 0 && !usernameError;
  }, [password.length, username, usernameError]);

  const submit = useCallback(async () => {
    if (!canSubmit || busy) return;
    setBusy(true);
    onClearError();
    try {
      const resp = await postJson<AdminResponse<LoginResponse>, { username: string; password: string }>(
        "/api/login",
        { username: username.trim(), password: password.slice(0, MAX_PASSWORD_CHARS) },
      );
      if (!resp.success) {
        setAuthError(sanitizeErrorMessage(resp.message, "Invalid credentials"));
        setBusy(false);
        return;
      }
      setUsername("");
      setPassword("");
      setAuthRequired(false);
      setAuthError(null);
      if (resp.data?.requires_password_change) {
        setNavTab("configuration");
      }
    } catch (e: any) {
      const msg = sanitizeErrorMessage(e?.message ?? e, "Login failed");
      const isServerError = e instanceof ApiError && typeof e.status === "number" && e.status >= 500;
      if (isServerError || msg.includes("fetch") || msg.includes("Failed") || msg.includes("NetworkError")) {
        setAuthError("Server unreachable. Check that backend is running and reachable.");
      } else {
        setAuthError(msg || "Login failed");
      }
    } finally {
      setBusy(false);
    }
  }, [busy, canSubmit, onClearError, password, setAuthError, setAuthRequired, setNavTab, username]);

  return (
    <AppDialog
      isOpen={open}
      isDismissable={false}
      hideCloseButton
    >
      <AppDialogContent>
        {() => (
          <form
            className="contents"
            autoComplete="on"
            onSubmit={(e) => {
              e.preventDefault();
              void submit();
            }}
          >
            <AppDialogHeader className="flex flex-col gap-1">
              <div className="text-[14px] font-semibold text-text-primary dashboard-heading-sans">Admin Login</div>
              <div className="text-[11px] text-black dashboard-heading-sans">
                Enter admin credentials to access server configuration.
              </div>
            </AppDialogHeader>
            <AppDialogBody className="gap-3">
              <TextInput
                label="Username"
                name="username"
                maxLength={MAX_USERNAME_CHARS}
                autoComplete="username"
                error={usernameError}
                value={username}
                onChange={(v) => { setUsername(v); onClearError(); }}
                labelClassName="text-[11px] font-semibold text-black dashboard-heading-sans"
              />
              <TextInput
                label="Password"
                type="password"
                name="password"
                maxLength={MAX_PASSWORD_CHARS}
                autoComplete="current-password"
                value={password}
                onChange={(v) => { setPassword(v); onClearError(); }}
                labelClassName="text-[11px] font-semibold text-black dashboard-heading-sans"
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    submit();
                  }
                }}
              />
            </AppDialogBody>
            <AppDialogFooter>
              <Btn
                type="submit"
                variant="accent"
                size="md"
                disabled={!canSubmit}
                loading={busy}
              >
                Login
              </Btn>
            </AppDialogFooter>
          </form>
        )}
      </AppDialogContent>
    </AppDialog>
  );
}

// apps/svelte-admin/src/lib/components/LoginModal.svelte
<script lang="ts">
  import { Dialog } from "bits-ui";
  import { cn, ripple } from "@quicfuscate/ui";
  import TextInput from "$lib/components/ui/TextInput.svelte";
  import {
    setAuthRequired,
    setAuthError,
    setActiveTab,
  } from "$lib/stores/app.svelte";
  import { ApiError, postJson, sanitizeErrorMessage } from "$lib/api";
  import type { AdminResponse } from "$lib/types";

  interface Props {
    open: boolean;
    error: string | null;
    onClearError: () => void;
  }

  let { open, error, onClearError }: Props = $props();

  type LoginResponse = { user: string; requires_password_change?: boolean };
  const MAX_USERNAME_CHARS = 64;
  const MAX_PASSWORD_CHARS = 256;
  const REJECT_FEEDBACK_MS = 520;

  let username = $state("admin");
  let password = $state("");
  let busy = $state(false);
  let feedbackPhase = $state<"idle" | "reject">("idle");
  let dialogEl: HTMLDivElement | undefined = $state();
  let rejectTimeoutId: number | null = null;
  let prefersReducedMotion = $state(false);

  $effect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    prefersReducedMotion = mq.matches;
    const handler = (e: MediaQueryListEvent) => { prefersReducedMotion = e.matches; };
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  });

  const usernameError = $derived.by(() => {
    const u = username.trim();
    if (!u) return null;
    if (u.length > MAX_USERNAME_CHARS) return `Username too long [max ${MAX_USERNAME_CHARS} chars]`;
    if ([...u].some((ch) => /[\x00-\x1F\x7F]/.test(ch))) return "Username contains invalid characters";
    return null;
  });

  const canSubmit = $derived.by(() => {
    const u = username.trim();
    return u.length > 0 && u.length <= MAX_USERNAME_CHARS && password.length > 0 && !usernameError;
  });

  $effect(() => {
    if (!open) {
      feedbackPhase = "idle";
      return;
    }
    username = "admin";
    password = "";
    feedbackPhase = "idle";
  });

  $effect(() => {
    if (!open || !error) return;
    feedbackPhase = "reject";
    if (rejectTimeoutId !== null) window.clearTimeout(rejectTimeoutId);
    rejectTimeoutId = window.setTimeout(() => {
      feedbackPhase = "idle";
      rejectTimeoutId = null;
    }, REJECT_FEEDBACK_MS);

    // Auto-focus + select password field after reject
    window.requestAnimationFrame(() => {
      const pwInput = dialogEl?.querySelector<HTMLInputElement>('input[type="password"]');
      if (pwInput) {
        pwInput.focus();
        pwInput.select();
      }
    });

    // Shake animation via CSS (or opacity pulse for reduced motion)
    if (dialogEl) {
      if (prefersReducedMotion) {
        dialogEl.classList.remove("qf-pulse-reject");
        void dialogEl.offsetWidth;
        dialogEl.classList.add("qf-pulse-reject");
      } else {
        dialogEl.classList.remove("qf-shake");
        void dialogEl.offsetWidth;
        dialogEl.classList.add("qf-shake");
      }
    }
  });

  async function submit() {
    if (!canSubmit || busy) return;
    busy = true;
    onClearError();
    try {
      const resp = await postJson<AdminResponse<LoginResponse>, { username: string; password: string }>(
        "/api/login",
        { username: username.trim(), password: password.slice(0, MAX_PASSWORD_CHARS) },
      );
      if (!resp.success) {
        setAuthError(sanitizeErrorMessage(resp.message, "Invalid credentials"));
        busy = false;
        return;
      }
      username = "";
      password = "";
      setAuthRequired(false);
      setAuthError(null);
      if (resp.data?.requires_password_change) {
        setActiveTab("configuration");
      }
    } catch (e: unknown) {
      const msg = sanitizeErrorMessage(
        e instanceof Error ? e.message : String(e),
        "Login failed",
      );
      const isServerError = e instanceof ApiError && typeof e.status === "number" && e.status >= 500;
      if (isServerError || msg.includes("fetch") || msg.includes("Failed") || msg.includes("NetworkError")) {
        setAuthError("Server unreachable. Check that backend is running and reachable.");
      } else {
        setAuthError(msg || "Login failed");
      }
    } finally {
      busy = false;
    }
  }
</script>


<Dialog.Root {open} onOpenChange={() => {}}>
  <Dialog.Portal to="#qf-app-stage">
    <Dialog.Overlay
      class="absolute inset-0 z-50 bg-black/18 animate-in fade-in-0 duration-150"
      style="backdrop-filter: blur(6px); -webkit-backdrop-filter: blur(6px);"
    />
    <Dialog.Content
      class="qf-login-dialog-shell dialog-surface absolute left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 rounded-[18px] w-[min(22.75rem,calc(100vw-2rem))] animate-in fade-in-0 zoom-in-95 duration-200"
      data-auth-feedback={feedbackPhase}
    >
      <div bind:this={dialogEl} class="qf-login-motion-shell w-full">
        <form
          class="flex w-full min-w-0 flex-col"
          autocomplete="on"
          onsubmit={(e) => { e.preventDefault(); void submit(); }}
        >
          <span class="sr-only" aria-live="polite" aria-atomic="true">
            {error ? "Login failed. Check your credentials and try again." : ""}
          </span>
          <div class="dialog-header-pad flex flex-col gap-1">
            <div class="text-[14px] font-semibold text-text-primary dashboard-heading-sans">Admin Login</div>
            <div class="text-[11px] text-black dashboard-heading-sans">
              Enter admin credentials to access server configuration.
            </div>
          </div>
          <div class="dialog-body-pad space-y-3">
            <TextInput
              label="Username"
              id="admin-login-username"
              name="username"
              maxLength={MAX_USERNAME_CHARS}
              autoComplete="username"
              autoFocus={true}
              value={username}
              className="qf-login-field"
              ariaInvalid={feedbackPhase === "reject"}
              onchange={(v) => { username = v; onClearError(); }}
              labelClassName="text-[11px] font-semibold text-black dashboard-heading-sans"
            />
            <TextInput
              label="Password"
              id="admin-login-password"
              type="password"
              name="password"
              maxLength={MAX_PASSWORD_CHARS}
              autoComplete="current-password"
              value={password}
              className="qf-login-field"
              ariaInvalid={feedbackPhase === "reject"}
              onchange={(v) => { password = v; onClearError(); }}
              onkeydown={(e) => { if (e.key === "Enter") { e.preventDefault(); void submit(); } }}
              labelClassName="text-[11px] font-semibold text-black dashboard-heading-sans"
            />
          </div>
          <div class="dialog-footer-pad">
            <button
              use:ripple={{ color: "light" }}
              type="submit"
              disabled={!canSubmit || busy}
              class={cn(
                "qf-login-submit action-btn-base action-save-btn inline-flex items-center justify-center font-medium h-8 px-4 text-[12px] gap-2 w-full",
                (!canSubmit || busy) ? "opacity-35 cursor-not-allowed" : "cursor-pointer",
              )}
            >
              {#if busy}
                <span class="h-3 w-3 border-2 border-current border-t-transparent rounded-full animate-spin"></span>
              {/if}
              Login
            </button>
          </div>
        </form>
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
