// packages/ui/Switch.svelte
<script lang="ts">
  import { cn } from "./cn";

  interface Props {
    checked?: boolean;
    disabled?: boolean;
    onchange?: (checked: boolean) => void;
    class?: string;
    label?: string;
  }

  let { checked = false, disabled = false, onchange, class: className, label }: Props = $props();
</script>

<button
  type="button"
  role="switch"
  aria-checked={checked}
  aria-label={label ?? "Toggle"}
  {disabled}
  onclick={() => { if (!disabled) onchange?.(!checked); }}
  class={cn(
    "relative inline-flex h-[18px] w-[32px] shrink-0 rounded-full transition-[background-color,box-shadow] duration-260 ease-[cubic-bezier(0.22,1,0.36,1)] cursor-pointer overflow-hidden",
    checked
      ? "bg-accent shadow-[inset_0_1px_0_rgba(255,255,255,0.22),0_0_0_1px_rgba(99,102,241,0.28)]"
      : "bg-surface-4 shadow-[inset_0_1px_2px_rgba(0,0,0,0.08)]",
    disabled && "opacity-35 cursor-not-allowed",
    className,
  )}
>
  <span
    class={cn(
      "absolute top-[2px] h-[14px] w-[14px] rounded-full bg-white transition-transform duration-260 ease-[cubic-bezier(0.22,1,0.36,1)] will-change-transform",
      checked ? "translate-x-[16px]" : "translate-x-[2px]",
    )}
    style="box-shadow: 0 1px 3px rgba(0,0,0,0.16), inset 0 1px 0 rgba(255,255,255,0.58);"
  ></span>
</button>

// apps/desktop/src/components/ui/switch.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

interface SwitchProps {
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
  className?: string;
}

const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  ({ className, checked, onCheckedChange, disabled, ...props }, ref) => (
    <button
      ref={ref}
      type="button"
      role="switch"
      aria-checked={checked}
      disabled={disabled}
      onClick={() => !disabled && onCheckedChange?.(!checked)}
      className={cn(
        "relative inline-flex h-[18px] w-[32px] shrink-0 rounded-full transition-[box-shadow] duration-200 ease-[cubic-bezier(0.34,1.56,0.64,1)] cursor-pointer overflow-hidden",
        "bg-surface-4",
        checked ? "shadow-none" : "shadow-[inset_0_1px_2px_rgba(0,0,0,0.08)]",
        disabled && "opacity-35 cursor-not-allowed",
        className,
      )}
      {...props}
    >
      <span
        className={cn(
          "pointer-events-none absolute inset-0 rounded-full bg-accent origin-left transition-transform duration-200 ease-[cubic-bezier(0.34,1.56,0.64,1)] will-change-transform",
          checked ? "scale-x-100" : "scale-x-0",
        )}
      />
      <span
        className={cn(
          "absolute top-[2px] h-[14px] w-[14px] rounded-full bg-white transition-transform duration-200 ease-[cubic-bezier(0.34,1.56,0.64,1)] will-change-transform",
          checked ? "translate-x-[16px]" : "translate-x-[2px]",
        )}
        style={{ boxShadow: "0 1px 3px rgba(0,0,0,0.15)" }}
      />
    </button>
  ),
);
Switch.displayName = "Switch";

export { Switch };
