// apps/desktop/src/components/ui/confirm-dialog.tsx
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter } from "@heroui/react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useStageModalPortal, withStageModalClassNames } from "@/lib/stage-modal";
const RIPPLE_ACTION_DELAY_MS = 88;

interface ConfirmDialogProps {
  open: boolean;
  title: string;
  message: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: "default" | "danger";
  onConfirm: () => void;
  onCancel: () => void;
  loading?: boolean;
}

export function ConfirmDialog({
  open,
  title,
  message,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  variant = "default",
  onConfirm,
  onCancel,
  loading = false,
}: ConfirmDialogProps) {
  const portalContainer = useStageModalPortal();

  return (
    <Modal
      isOpen={open}
      onClose={onCancel}
      backdrop="blur"
      hideCloseButton
      size="sm"
      portalContainer={portalContainer}
      classNames={withStageModalClassNames()}
    >
      <ModalContent className="glass border border-edge shadow-xl rounded-[18px] dialog-typography dialog-surface">
        {() => (
          <>
            <ModalHeader className="dialog-header-pad flex flex-col gap-1">
              <div className="text-[13px] font-semibold text-black dashboard-heading-sans">{title}</div>
            </ModalHeader>
            <ModalBody className="dialog-body-pad">
              <p className="text-[12px] text-black leading-relaxed">{message}</p>
            </ModalBody>
            <ModalFooter className="dialog-footer-pad">
              <Button
                type="button"
                onClick={() => {
                  window.setTimeout(onCancel, RIPPLE_ACTION_DELAY_MS);
                }}
                disabled={loading}
                className="inline-flex items-center rounded-lg px-3 py-1.5 border text-[11px] font-semibold transition-all action-refresh-btn disabled:opacity-55"
              >
                {cancelLabel}
              </Button>
              <Button
                type="button"
                onClick={() => {
                  window.setTimeout(onConfirm, RIPPLE_ACTION_DELAY_MS);
                }}
                disabled={loading}
                className={cn(
                  "inline-flex items-center rounded-lg px-3 py-1.5 border text-[11px] font-semibold transition-all disabled:opacity-55",
                  variant === "danger" ? "action-disconnect-btn" : "action-save-btn",
                )}
              >
                {loading ? "..." : confirmLabel}
              </Button>
            </ModalFooter>
          </>
        )}
      </ModalContent>
    </Modal>
  );
}

// packages/ui/ConfirmDialog.svelte
<script lang="ts">
  import { Dialog } from "bits-ui";
  import { ripple } from "./ripple";

  interface Props {
    open: boolean;
    title: string;
    message: string;
    confirmLabel?: string;
    cancelLabel?: string;
    destructive?: boolean;
    portalTarget?: string;
    onconfirm: () => void;
    oncancel: () => void;
  }

  let {
    open = $bindable(false),
    title,
    message,
    confirmLabel = "Confirm",
    cancelLabel = "Cancel",
    destructive = false,
    portalTarget,
    onconfirm,
    oncancel,
  }: Props = $props();

  const pos = $derived(portalTarget ? "absolute" : "fixed");
</script>

<Dialog.Root bind:open>
  <Dialog.Portal to={portalTarget}>
    <Dialog.Overlay
      class="{pos} inset-0 z-50 bg-black/18 animate-in fade-in-0 duration-150"
      style="backdrop-filter: blur(6px); -webkit-backdrop-filter: blur(6px);"
    />
    <Dialog.Content
      class="dialog-surface dialog-typography {pos} left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 glass border border-edge shadow-xl rounded-[18px] w-[340px] animate-in fade-in-0 zoom-in-95 duration-200"
    >
      <div class="dialog-header-pad">
        <Dialog.Title class="text-[13px] font-semibold text-black dashboard-heading-sans">
          {title}
        </Dialog.Title>
      </div>
      <div class="dialog-body-pad">
        <p class="text-[12px] text-black leading-relaxed">{message}</p>
      </div>
      <div class="dialog-footer-pad">
        <button use:ripple={{ color: "light" }} class="inline-flex items-center rounded-lg px-3 py-1.5 border text-[11px] font-semibold transition-all action-refresh-btn flex-1" onclick={() => { window.setTimeout(oncancel, 88); }}>
          {cancelLabel}
        </button>
        <button
          use:ripple={{ color: "light" }}
          class="inline-flex items-center rounded-lg px-3 py-1.5 border text-[11px] font-semibold transition-all {destructive ? 'action-disconnect-btn' : 'action-save-btn'} flex-1"
          onclick={() => { window.setTimeout(onconfirm, 88); }}
        >
          {confirmLabel}
        </button>
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
